kind: Namespace
apiVersion: v1
metadata:
  name: ns-server
  labels:
    name: ns-server
---
kind: Namespace
apiVersion: v1
metadata:
  name: ns-storage
  labels:
    name: ns-storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ns-storage
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: one_mdp_2022
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: ns-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
  namespace: ns-storage
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M