apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: ns-server
  labels:
    name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-hello
        image: nicolasnanass/flask-hello:latest
        imagePullPolicy: Never
        env:
            - name: flaskapi-secrets
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db-root-password
            - name: db_name
              value: flaskapi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-hello
  type: LoadBalancer